version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./:/app/
    command: ["python", "main.py", "1"]

  inoutapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ./:/app/
    command: ["python", "pluj_wypluj_api.py"]
