version: '3.8'

services:
  db:
    image: postgres:15.2-alpine
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data:
    driver: local
